version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:${PG_PORT}"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_URL: postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend