CREATE USER p_braun WITH LOGIN PASSWORD 'd5pND8nqT5BbZiUC';
GRANT dekan TO p_braun;
CREATE USER m_rott WITH LOGIN PASSWORD 'C9WS2sHyarDjA8dz';
GRANT db_admin TO m_rott WITH ADMIN OPTION;
GRANT professor TO m_rott WITH ADMIN OPTION;
CREATE USER s_krause WITH LOGIN PASSWORD 'uZN3G6eMR5yr9pyq';
GRANT enrollment_secretary TO s_krause;
CREATE USER t_fischer WITH LOGIN PASSWORD 'Ynfd3C8Xn462cpZT';
GRANT secretary TO t_fischer;
CREATE USER s_biedermann WITH LOGIN PASSWORD 'KuFzw7uFGvLHe4';
GRANT professor TO s_biedermann;
