CREATE USER p_braun WITH LOGIN PASSWORD 'd5pND8nqT5BbZiUC' IN <db_name>;
GRANT p_braun TO dekan IN <db_name>;
CREATE USER m_rott WITH LOGIN PASSWORD 'C9WS2sHyarDjA8dz' IN <db_name>;
GRANT m_rott TO db_admin IN <db_name>;
CREATE USER s_krause WITH LOGIN PASSWORD 'uZN3G6eMR5yr9pyq' IN <db_name>;
GRANT s_krause TO enrollment_secretary IN <db_name>;
CREATE USER t_fischer WITH LOGIN PASSWORD 'Ynfd3C8Xn462cpZT' IN <db_name>;
GRANT t_fischer TO secretary IN <db_name>;
CREATE USER s_biedermann WITH LOGIN PASSWORD 'KuFzw7uFGvLHe4' IN <db_name>;
GRANT s_biedermann TO professor IN <db_name>;